### ISSUE TITLE
Create ship controls

### ISSUE THREAD

**Issue by boracayalex** [NikolineOlsen/slick2d-eclipse-seed#2]
Ship should controlled by rotating it and then adding thrust(force) from the direction of the thrusters. Ne

**Comment by NikolineOlsen** [comment]
hah sorry Alex, det var ikke meningen at jeg skulle skubbe dig ud af denne opgave! troede man kunne være flere på den. men jeg har også arbejdet med rotationen på skibet og ved ikke om det er det samme du også har arbejdet på?

**Comment by NikolineOlsen** [comment]
lidt om rotation: 
http://zetcode.com/gfx/java2d/transformations/ 
http://www.javalobby.org/java/forums/t19387.html
